// Generated by scripts/generate_matrix_frames.mjs from "maul.mp4".
// Do not edit by hand; regenerate this file from source media instead.

export const matrixFramesUrl = "/loading/matrixFrames.json";
export const matrixFrameRate = 12;
export const matrixColumns = 180;
export const matrixRows = 100;
export const matrixRenderBounds = {
  x: 18,
  y: 0,
  width: 143,
  height: 100,
} as const;
export const matrixLevels = 2;
export const matrixEncoding = "01";
export const matrixThemeMappings = {
  dark: {
    autoLevels: true,
    blackPoint: 0,
    brightness: 0,
    contrast: 1.2,
    gamma: 5,
    invert: false,
    levels: 2,
    minLevel: 0,
    threshold: 0.45,
    whitePoint: 255,
  },
  light: {
    autoLevels: true,
    blackPoint: 0,
    brightness: 0,
    contrast: 1.2,
    gamma: 5,
    invert: true,
    levels: 2,
    minLevel: 0,
    threshold: 0.45,
    whitePoint: 255,
  },
} as const;
