name: Release Selector

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Which release(s) to run"
        type: choice
        options: [cli, server, desktop, all]
        required: true
        default: cli

permissions:
  contents: read
  id-token: write

jobs:
  guard:
    uses: ./.github/workflows/_guard-release-branch.yml
    with:
      branch: release

  run-cli:
    needs: guard
    if: ${{ github.event.inputs.target == 'cli' || github.event.inputs.target == 'all' }}
    uses: ./.github/workflows/cli-release.yml
    secrets: inherit

  run-server:
    needs: guard
    if: ${{ github.event.inputs.target == 'server' || github.event.inputs.target == 'all'}}
    uses: ./.github/workflows/server-release.yml
    secrets: inherit

  run-desktop:
    needs: guard
    if: ${{ github.event.inputs.target == 'desktop' || github.event.inputs.target == 'all'}}
    uses: ./.github/workflows/desktop-release.yml
    secrets: inherit
